### ISSUE TITLE
Cookbook order might be wrong for version numbers over 10

### ISSUE THREAD

**Issue by brentm5** [cvent/knife-chef-retention#6]
I believe the sort for comparing version numbers is wrong so if version 1.10.1 exists and it is latest it would make anything below it not be chosen.  Need to look into this.

**Comment by majormoses** [comment]
I would suspect this is because of the behavior of: https://github.com/cvent/knife-chef-retention/blob/6e2feda49935bf1a836d9b69dac330acbca38b1d/lib/chef/knife/retention_cookbook.rb#L114 you might consider using `Gem::Version` as a comparison when sorting like this: https://github.com/majormoses/knife-cookbook-cleanup/blob/9d740fe6eeecbf880cae98c00ff361bde1580b9e/lib/chef/knife/cookbook_cleanup.rb#L52

**Comment by majormoses** [comment]
Here is a quick illustration here:
```
irb(main):001:0> %w(1.0.0 1.0.1 1.0.2 1.0.3 1.0.4 1.0.5 1.0.6 1.0.7 1.0.8 1.0.9 1.0.10 1.0.11).sort
=> ["1.0.0", "1.0.1", "1.0.10", "1.0.11", "1.0.2", "1.0.3", "1.0.4", "1.0.5", "1.0.6", "1.0.7", "1.0.8", "1.0.9"]
irb(main):002:0> %w(1.0.0 1.0.1 1.0.2 1.0.3 1.0.4 1.0.5 1.0.6 1.0.7 1.0.8 1.0.9 1.0.10 1.0.11).sort { |x, y| Gem::Version.new(x) <=> Gem::Version.new(y) }
=> ["1.0.0", "1.0.1", "1.0.2", "1.0.3", "1.0.4", "1.0.5", "1.0.6", "1.0.7", "1.0.8", "1.0.9", "1.0.10", "1.0.11"]

```

Not sure if anyone is still using or maintaining this but if you want I can probably submit a patch for it

**Comment by brentm5** [comment]
Feel free to submit a pr!
